<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PromotersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('promoters')->delete();
        
        \DB::table('promoters')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'KRN Promotions',
                'location' => 'Sunderland, England, United Kingdom',
                'postal_town' => 'Sunderland',
                'latitude' => '54.9058512',
                'longitude' => '-1.3828727',
                'logo_url' => '',
                'description' => 'KRN promotions is a metal based promotions company established in August 2023. Our goal is to bring new underground bands to different venues around the UK and show off what talent there is. We also dabble in the odd review for EPs, Singles and shows.',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Krispy Harper',
                'contact_number' => '00000000000',
                'contact_email' => 'kr.promotions.94@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/profile.php?id=100095401154890\\",\\"instagram\\":\\"https://www.facebook.com/profile.php?id=100095401154890\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => 'email',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'BeardBo & Get Heavy UK',
                'location' => 'Newcastle upon Tyne, Tyne and Wear, England, United Kingdom',
                'postal_town' => 'Newcastle',
                'latitude' => '54.9738474',
                'longitude' => '-1.6131572',
                'logo_url' => '',
                'description' => 'Est in 2021 Newcastle Based Live Video-Radio Show, Podcast & Reviews',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'contact@get-heavy-uk.co.uk',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Mangata Music',
                'location' => 'Nottingham, Nottinghamshire, England, United Kingdom',
                'postal_town' => 'Nottingham',
                'latitude' => '52.9534193',
                'longitude' => '-1.1496461',
                'logo_url' => '',
                'description' => 'Nottingham based live music promotions company, specialising in heavy music.',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Kris',
                'contact_number' => '00000000000',
                'contact_email' => 'info@mangatamusic.co.uk',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Rock The Foundry',
                'location' => 'Nottingham, Nottinghamshire, England, United Kingdom',
                'postal_town' => 'Nottingham',
                'latitude' => '52.9534193',
                'longitude' => '-1.1496461',
                'logo_url' => '',
                'description' => 'Rock The Foundry Metal Promotions organises single shows, all dayers and tours for rock/metal bands',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'rockthefoundry@outlook.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/rockthefoundrypromotions\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Lilith Promotions',
                'location' => 'Manchester, England, United Kingdom',
                'postal_town' => 'Manchester',
                'latitude' => '53.4794892',
                'longitude' => '-2.2451148',
                'logo_url' => '',
                'description' => 'For all enquires please email us lilithpromohq@gmail.com',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'lilithpromohq@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/profile.php?id=100089881453453\\",\\"instagram\\":\\"https://www.instagram.com/lilithpromotionshq/\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Heads Up North Manchester',
                'location' => 'Manchester, England, United Kingdom',
                'postal_town' => 'Manchester',
                'latitude' => '53.4794892',
                'longitude' => '-2.2451148',
                'logo_url' => '',
                'description' => 'Born and raised in Manchester, Heads up North are a new and fresh, all inclusive web-scene!',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/profile.php?id=61552663431410\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Shadow Fest Promotions',
                'location' => 'Bradford, England, United Kingdom',
                'postal_town' => 'Bradford',
                'latitude' => '53.7944229',
                'longitude' => '-1.7519186',
                'logo_url' => '',
                'description' => 'Female owned | Metalcore, deathcore, punk, pop punk promoter | Based in Bradford 🤘🏻🖤',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Jamie-Lee Hannon',
                'contact_number' => '07710817121',
                'contact_email' => 'shadowfestuk@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/profile.php?id=100095401154890\\",\\"instagram\\":\\"https://www.facebook.com/profile.php?id=100095401154890\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => 'email',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'North East Wales Metal Productions',
                'location' => 'Wales, United Kingdom',
                'postal_town' => 'Wales',
                'latitude' => '52.2928116',
                'longitude' => '-3.73893',
                'logo_url' => '',
                'description' => 'Metal promotions company situated in North East Wales. We aim to bring you bigger and better events featuring metal bands from across the world!',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'bookings@goodforaudio.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/N.E.WMetalProductions\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Mcintosh Inc Promotions',
                'location' => 'Blackpool, FY1 1DL, United Kingdom',
                'postal_town' => 'Blackpool',
                'latitude' => '53.8179442',
                'longitude' => '-3.0509812',
                'logo_url' => '',
                'description' => 'A new promotions company starting in Blackpool and sister company to McIntosh Inc Reviews and Mcintosh Bookings',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Gary',
                'contact_number' => '00000000000',
                'contact_email' => 'Info.mip.tech@gmail.com',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'LKmusic Promotions',
                'location' => 'Merseyside, England',
                'postal_town' => 'Mersyside',
                'latitude' => '53.407634735107',
                'longitude' => '-2.9840085506439',
                'logo_url' => '',
                'description' => 'LKmusic Promotions are brand new music promoters based in Merseyside',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'lkmusicpromotions@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/profile.php?id=100095401154890\\",\\"instagram\\":\\"https://www.facebook.com/profile.php?id=100095401154890\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => 'email',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => '0161 MUMC Promotions',
                'location' => 'Manchester, England, United Kingdom',
                'postal_town' => 'Manchester',
                'latitude' => '53.4794892',
                'longitude' => '-2.2451148',
                'logo_url' => '',
                'description' => 'We have created this page to allow underground bands from all over the world to promote themselves to an audience. We both promote bands and we put on lots of events around the Northwest. Feel free to message or email us if you require any help as a band
',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '07920446538',
                'contact_email' => '0161mumc@gmail.com',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Atheris Promotions',
                'location' => 'Bristol, City of Bristol, England, United Kingdom',
                'postal_town' => 'Bristol',
                'latitude' => '51.4538022',
                'longitude' => '-2.5972985',
                'logo_url' => '',
                'description' => 'Event promoters based in Bristol specialising in metal and heavy bands who want to start making some headway in the scene. Get in touch if you want to collaborate!',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'atherispromotions@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/atherispromotions\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Blood Eagle Promotions',
                'location' => 'Manchester, England, United Kingdom',
                'postal_town' => 'Manchester',
                'latitude' => '53.4794892',
                'longitude' => '-2.2451148',
                'logo_url' => '',
                'description' => 'Manchester based music Promotor',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'bloodeaglepromotions@gmail.com',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Deadsoul Promotions',
                'location' => 'Ipswich, Suffolk, England, United Kingdom',
                'postal_town' => 'Ipswich',
                'latitude' => '52.0579324',
                'longitude' => '1.1528095',
                'logo_url' => '',
                'description' => 'Booking & Promotions company based in Ipswich, UK. Bringing Metal to Ipswich & beyond since 2005!',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'deadsoulpromotions@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/deadsoulpromotions\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Jackhammer Promotions',
                'location' => 'Brighton, East Sussex, England, United Kingdom',
                'postal_town' => 'Brighton',
                'latitude' => '50.8214626',
                'longitude' => '-0.1400561',
                'logo_url' => '',
                'description' => 'Live Events | Booking Agency | Band Management',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'mark784wood@googlemail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/jackhammerpromotions\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Luna Promotions',
                'location' => 'Norwich, Norfolk, England, United Kingdom',
                'postal_town' => 'Norwich',
                'latitude' => '52.6285576',
                'longitude' => '1.2923954',
                'logo_url' => '',
                'description' => 'Providing Music Promotion in Norwich',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'lunapromotions20@gmail.com',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Metathetic Music',
                'location' => 'Durham, England, United Kingdom',
                'postal_town' => 'Durham',
                'latitude' => '54.666667',
                'longitude' => '-1.75',
                'logo_url' => '',
                'description' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Will',
                'contact_number' => '00000000000',
                'contact_email' => 'will@methatheticmusic.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://facebook.com/metatheticmusic\\",\\"instagram\\":\\"https://instagram.com/metathetic_music\\",\\"tiktok\\":\\"https://tiktok.com/@metatheticmusic\\",\\"website\\":\\"https://metatheticmusic.co.uk/\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'No Play Promotions',
                'location' => 'Liverpool, England, United Kingdom',
                'postal_town' => 'Liverpool',
                'latitude' => '53.4071991',
                'longitude' => '-2.99168',
                'logo_url' => '',
                'description' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'contact@noplay.uk',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Reaction Management',
                'location' => 'Scotland, United Kingdom',
                'postal_town' => 'Scotland',
                'latitude' => '56.7861112',
                'longitude' => '-4.1140518',
                'logo_url' => '',
                'description' => 'Management | Consultancy | Promotion | Digital Marketing | Tour Booking',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'jay.burnett@reaction-management.com',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Riffolution Promotions',
                'location' => 'Manchester, England, United Kingdom',
                'postal_town' => 'Manchester',
                'latitude' => '53.4794892',
                'longitude' => '-2.2451148',
                'logo_url' => '',
                'description' => 'UK event promotions, Manchester based. Desert Rock/Stoner/Doom/Psychedelic/Sludge',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Tapestry Promotions',
                'location' => 'Manchester, England, United Kingdom',
                'postal_town' => 'Manchester',
                'latitude' => '53.4794892',
                'longitude' => '-2.2451148',
                'logo_url' => '',
                'description' => 'Manchester based promotions/events company.',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'dan@tapestrypromotions.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://www.tapestrypromotions.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/TapestryPromotions\\",\\"twitter\\":\\"https://twitter.com/TapestryPromo\\",\\"instagram\\":\\"https://www.instagram.com/tapestrypromotions/\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Torturous Promotions',
                'location' => 'Nottingham, Nottinghamshire, England, United Kingdom',
                'postal_town' => 'Nottingham',
                'latitude' => '52.9534193',
                'longitude' => '-1.1496461',
                'logo_url' => '',
                'description' => 'Promoting Metal gigs in Nottingham since 2009.',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Phil Core',
                'contact_number' => '00000000000',
                'contact_email' => 'philcore98@gmail.com',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'TwoFace Promotions',
                'location' => 'Oxford, Oxfordshire, England, United Kingdom',
                'postal_town' => 'Oxford',
                'latitude' => '51.7520131',
                'longitude' => '-1.2578499',
                'logo_url' => '',
                'description' => 'Trying to revive Oxfords metal scene!',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'twofacepromotions@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/twofacepromo\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Unhinged Promotions',
                'location' => 'Manchester, England, United Kingdom',
                'postal_town' => 'Manchester',
                'latitude' => '53.4794892',
                'longitude' => '-2.2451148',
                'logo_url' => '',
                'description' => 'Unhinged are Manchester\'s newest up and coming metal management, artist development, booking, and promotions team. Founded in 2024 with the aim of supporting both local and out of town metal bands of all shapes and sizes.',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'unhingedpromotions@gmail.com',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'UK Thrashers',
                'location' => 'Coventry, England, United Kingdom',
                'postal_town' => 'Coventry',
                'latitude' => '52.4081812',
                'longitude' => '-1.510477',
                'logo_url' => '',
                'description' => 'Now Featuring UK Death Dealers - Thrash and Death Metal...from the UK and beyond, News, Reviews, Interviews, Management, Booking & PR',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Neil',
                'contact_number' => '07857627220',
                'contact_email' => 'ukthrashers@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/ukthrashers/\\",\\"instagram\\":\\"https://instagram.com/ukthrashers\\",\\"website\\":\\"https://ukthrashers.org/\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Novacaine Festival',
                'location' => 'Sheffield, England, United Kingdom',
                'postal_town' => 'Sheffield',
                'latitude' => '53.3806626',
                'longitude' => '-1.4702278',
                'logo_url' => '',
                'description' => '🎶 Welcome to Novacaine Festival: The UK\'s New Music Discovery Festival! 🎶 Join us on Saturday, October 4th, 2025, at the iconic Corporation in Sheffield for an unforgettable day of emerging talent and fresh sounds.',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Scott O’Shea',
                'contact_number' => '00000000000',
                'contact_email' => 'novacainepr@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/WeAreNovacaine/\\",\\"instagram\\":\\"https://www.instagram.com/wearenovacaine/\\",\\"tiktok\\":\\"https://www.tiktok.com/@wearenovacaine\\",\\"twitter\\":\\"https://twitter.com/wearenovacaine\\",\\"website\\":\\"https://www.novacaine.co.uk/\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'UK Death Dealers',
                'location' => 'London, United Kingdom',
                'postal_town' => 'London',
                'latitude' => '51.5074456',
                'longitude' => '-0.1277653',
                'logo_url' => '',
                'description' => 'UK Death Dealers we are all about supporting UK Death Metal! There’ll be news, reviews and more!',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'ukdeathdealers@outlook.com',
                'contact_link' => '"{}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Venom Fest',
                'location' => 'Newcastle upon Tyne, Tyne and Wear, England, United Kingdom',
                'postal_town' => 'Newcastle',
                'latitude' => '54.9738474',
                'longitude' => '-1.6131572',
                'logo_url' => '',
                'description' => 'NORTH EAST EVENTS. LIVE METAL, GORE BURLESQUE, FIRE PERFORMERS AND ALT MARKETS',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'Thorn Faustus',
                'contact_number' => '00000000000',
                'contact_email' => 'thornfaustus@venomevents.com',
                'contact_link' => '"{\\"website\\":\\"https://venomevents.bigcartel.com/\\",\\"facebook\\":\\"https://m.facebook.com/61553342583087/\\",\\"instagram\\":\\"https://instagram.com/venom_fest\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Metal & Rock Gigs Liverpool',
                'location' => 'Liverpool, England, United Kingdom',
                'postal_town' => 'Liverpool',
                'latitude' => '53.4071991',
                'longitude' => '-2.99168',
                'logo_url' => '',
                'description' => 'A central location to share and collate all Metal/Rock/Alternative shows happening in Liverpool',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/profile.php?id=100090282892831\\",\\"instagram\\":\\"https://instagram.com/metalrockgigsliverpool\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Scaredy Cat Promotions',
                'location' => 'London, United Kingdom',
                'postal_town' => 'London',
                'latitude' => '51.5074456',
                'longitude' => '-0.1277653',
                'logo_url' => '',
            'description' => 'Good gigs for good people. (fka Grim Heart Promotions)',
                'packages' => NULL,
                'my_venues' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'genre' => '{}',
                'band_type' => '[]',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'scaredycatpromo@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/grimheartpromo\\",\\"instagram\\":\\"https://www.instagram.com/scaredycatpromo/\\"}"',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
        ));
        
        
    }
}