<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VenuesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('venues')->delete();
        
        \DB::table('venues')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Corporation',
                'location' => 'Corporation, Milton Street, Sheffield City Centre, Sheffield, UK',
                'postal_town' => 'Sheffield',
                'longitude' => '-1.477934',
                'latitude' => '53.376263',
                'w3w' => 'hobby.lifts.shower',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01142760262',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://corporation.org.uk/\\",\\"facebook\\":\\"https://www.facebook.com/CorporationSheffield\\",\\"instagram\\":\\"https://www.instagram.com/corpsheffield/\\",\\"tiktok\\":\\"https://www.tiktok.com/@corporationnightclub\\"}"',
                'description' => 'Home of the Blue Pint. Get Gig Tickets -https://corporation.org.uk/live-gigs/ Join us Monday, Friday and Saturday for multiple rooms of music & some of the cheapest club night drinks in Sheff - https://corporation.org.uk/club-night-tickets/',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Dove and Rainbow',
                'location' => 'The Dove & Rainbow, Hartshead Square, Sheffield City Centre, Sheffield, UK',
                'postal_town' => 'Sheffield',
                'longitude' => '-1.363856',
                'latitude' => '53.348082',
                'w3w' => 'broken.aside.wing',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'Keith',
                'contact_number' => '01142721594',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://doveandrainbow.com/\\",\\"facebook\\":\\"https://www.facebook.com/doveandrainbow\\",\\"instagram\\":\\"https://www.instagram.com/thedoveandrainbow/\\"}"',
                'description' => 'Sheffield\'s friendly City Centre Rock Pub, and Alternative Community Hub is hidden away behind Spoons',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Code',
                'location' => 'Code Sheffield, Eyre Street, Sheffield City Centre, Sheffield, UK',
                'postal_town' => 'Sheffield',
                'longitude' => '-1.472182',
                'latitude' => '53.375299',
                'w3w' => 'broad.boats.loaded',
                'capacity' => '2000',
            'in_house_gear' => 'Full Flare Audio Sound, x2 Pioneer CDJ2000NXS2, x1 DJM900NXS2, LED Ceiling, CO2 Jets, Confetti System, 38 Moving Spots & Washes, LED Strobes & Blinders, Projection Mapping, x3 Lasers (x2 2W & x1 10W)',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01142720097',
                'contact_email' => 'info@codesheffield.com',
                'contact_link' => '"{\\"website\\":\\"https://www.codesheffield.com/\\",\\"facebook\\":\\"https://www.facebook.com/sheffieldcode\\",\\"instagram\\":\\"https://www.instagram.com/codesheffield/\\",\\"twitter\\":\\"https://www.twitter.com/codesheffield\\",\\"tiktok\\":\\"https://www.tiktok.com/@codesheffield\\",\\"snapchat\\":\\"https://www.snapchat.com/add/codesheffield\\"}"',
                'description' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'West Street Live',
                'location' => 'West Street Live, West Street, Sheffield City Centre, Sheffield, UK',
                'postal_town' => 'Sheffield',
                'longitude' => '-1.475295',
                'latitude' => '53.38108',
                'w3w' => 'pull.excuse.insist',
                'capacity' => '0',
            'in_house_gear' => 'Mixing Desk: Allen and Heath GL2400, Front Of House: LA Audio DLX260, LA Audio EQ231G, Lab Gruppen C88:4, 2 x HK Audio CT 115, 4 x HK Audio CT 118 Sub, Monitoring: 2x DBX 231s, 4x Hk Audio L5 112XA, House Bass Rig: Peavey Session Bass, SWR 4×10, House Drum Kit: Pearl Export 4 piece, Microphones: 6 x Shure SM 57, 3 x The T.bone MB-75 Beta, 1 x Sennheiser e602-ii, 3 x AKG P4, 2 x Sennheiser e606, 1 x Takstar PCM-6100, DI: Behringer Ultra-Di Pro (8 Inputs), Lighting Rig: 2 x robe show lighting spot’s, 2 x lanta Saturn 5 disco, 3x lanta LED stage lights, Qtx light DMX-x10 controller',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01142492785',
                'contact_email' => 'mentholmans@hotmail.com',
                'contact_link' => '"{\\"website\\":\\"http://weststreetlive.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/WestStreetLive\\",\\"twitter\\":\\"https://twitter.com/WestStreetLive\\",\\"instagram\\":\\"https://www.instagram.com/weststreetlive\\"}"',
                'description' => 'West Street Live is a live music venue and late bar/club in Sheffield, open 7 days a week.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Church',
                'location' => 'Church - Temple of Fun, Rutland Way, Sheffield, UK',
                'postal_town' => 'Sheffield',
                'longitude' => '-1.479347',
                'latitude' => '53.392626',
                'w3w' => 'eggs.struck.churn',
                'capacity' => '220',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '07521610842',
                'contact_email' => 'info@templeof.fun',
                'contact_link' => '"{\\"website\\":\\"https://templeof.fun/\\",\\"facebook\\":\\"https://www.facebook.com/TempleOfFun/\\",\\"instagram\\":\\"https://www.instagram.com/templeof.fun\\",\\"tiktok\\":\\"https://www.tiktok.com/@templeof.fun\\",\\"twitter\\":\\"https://twitter.com/templeof_fun\\"}"',
                'description' => 'Voted \'Best Vegan/Vegetarian Restaurant\' in Sheffield\'s Exposed Awards.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Hagglers Corner',
                'location' => 'Hagglers Corner, Queens Road, Lowfield, Sheffield, UK',
                'postal_town' => 'Sheffield',
                'longitude' => '-1.4716564',
                'latitude' => '53.3646957',
                'w3w' => 'suffice.boxer.adults',
                'capacity' => '100',
                'in_house_gear' => 'Sound System',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '07968822654',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://hagglerscorner.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/hagglers.corner\\",\\"instagram\\":\\"https://www.instagram.com/hagglers_corner_/\\",\\"twitter\\":\\"https://www.twitter.com/hagglerscorner\\"}"',
                'description' => '✨Cafe by Day, Party by Night
🍸Bar/Food/Music Venue
🎵Record Shop
🏆Award Winning Courtyard',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Here We Aren\'t',
                'location' => 'Here We Aren\'t, Godric Square, Peterborough, UK',
                'postal_town' => 'Peterborough',
                'longitude' => '-6.0333311',
                'latitude' => '54.2166524',
                'w3w' => 'pumps.drum.vision',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '07956283752',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://www.herewearent.com/\\",\\"facebook\\":\\"https://www.facebook.com/herewearent\\",\\"twitter\\":\\"https://www.twitter.com/here_we_arent\\",\\"instagram\\":\\"https://www.instagram.com/here_we_arent\\"}"',
                'description' => 'Here We Aren\'t works to record, promote, sell and distribute visual and aural art in the Peterborough area',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'The Metal Monocle',
                'location' => 'The Metal Monocle, Braunstone Gate, Leicester, UK',
                'postal_town' => 'Leicester',
                'longitude' => '-1.13169',
                'latitude' => '52.6386',
                'w3w' => 'swift.silks.candle',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'Tommy/ Caroline',
                'contact_number' => '01164292445',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{}"',
                'description' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Firebug',
                'location' => 'Firebug, Millstone Lane, Leicester, UK',
                'postal_town' => 'Leicester',
                'longitude' => '-1.1345031',
                'latitude' => '52.6330719',
                'w3w' => 'fires.drove.silent',
                'capacity' => '100',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'Kat Frater',
                'contact_number' => '1162551228',
                'contact_email' => 'info@firebugbar.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://firebugbar.net/\\",\\"facebook\\":\\"https://www.facebook.com/FirebugBar/\\",\\"instagram\\":\\"https://www.instagram.com/firebugbarleic/\\",\\"twitter\\":\\"https://www.twitter.com/FireBugBar\\"}"',
                'description' => 'FOOD - DRINK - COCKTAILS - LIVE MUSIC - COMEDY',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Duffy\'s Bar',
                'location' => 'Duffy\'s Bar, Pocklingtons Walk, Leicester, UK',
                'postal_town' => 'Leicester',
                'longitude' => '-1.13169',
                'latitude' => '52.6386',
                'w3w' => 'next.miles.wooden',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01618816789',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://www.ents24.com/manchester-events/duffys-bar-chorlton\\",\\"facebook\\":\\"https://www.facebook.com/duffysbar.chorlton/\\"}"',
                'description' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'The Hairy Dog',
                'location' => 'The Hairy Dog, Becket Street, Derby, UK',
                'postal_town' => 'Derby',
                'longitude' => '-1.3587912',
                'latitude' => '53.4327034',
                'w3w' => 'eggs.noon.enhancement',
                'capacity' => '0',
                'in_house_gear' => 'Sound System, Lighting Rig',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'Nicole Butler',
                'contact_number' => '07446845555',
                'contact_email' => 'nicole@hairydogvenue.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://hairydogvenue.co.uk/\\",\\"instagram\\":\\"https://www.instagram.com/thehairydogderby\\",\\"facebook\\":\\"https://www.facebook.com/thehairydogderby\\"}"',
                'description' => 'The Hairy Dog is the small music venue with a big sound in the heart of Derby.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Tap \'n\' Tumbler',
                'location' => 'Tap & Tumbler, Wollaton Street, Nottingham, UK',
                'postal_town' => 'Nottingham',
                'longitude' => '-1.1534573',
                'latitude' => '52.9550735',
                'w3w' => 'dozen.arena.move',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01159413414',
                'contact_email' => '7050@greeneking.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://www.greeneking.co.uk/pubs/nottinghamshire/tap-and-tumbler\\",\\"facebook\\":\\"https://www.facebook.com/TapnTumblerNottingham/\\"}"',
                'description' => 'The Tap & Tumbler is a pub at the heart of Nottingham',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'The Old Salutation Inn',
                'location' => 'The Old Salutation, Maid Marian Way, Nottingham, UK',
                'postal_town' => 'Nottingham',
                'longitude' => '-1.1517673',
                'latitude' => '52.9508688',
                'w3w' => 'banana.factor.scar',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01159881948',
                'contact_email' => 'Thesalutationvenue@gmail.com',
                'contact_link' => '"{\\"website\\":\\"http://www.nottinghamgigguide.com/venue/nottingham/salutation_inn\\",\\"facebook\\":\\"https://www.facebook.com/TheSalNotts\\"}"',
                'description' => 'Welcome to The Old Salutation Inn.
To keep up with our events, offers and for any band inquiries, give the page a like!',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'The Old Cold Store',
                'location' => 'The Old Cold Store, Queensbridge Road, Nottingham, UK',
                'postal_town' => 'Nottingham',
                'longitude' => '-1.1487384',
                'latitude' => '52.9533834',
                'w3w' => 'chose.rising.congratulations',
                'capacity' => '0',
                'in_house_gear' => 'Sound System, Projector',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01159850611',
                'contact_email' => 'vatandfiddleevents@castlerockbrewery.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://www.castlerockbrewery.co.uk/function-rooms/old-cold-store/\\"}"',
                'description' => 'The Old Cold Store gets its name from its former line of service to the brewery – a large storage area for keeping beer cold! Thanks to expansion, the Old Cold Store is now an industrial and minimalist function facility available for private hire. It is ideally located just a short stroll from Nottingham station.
Essentially a supersized blank canvas, the Old Cold Store has a reputation for live music events thanks to its work with Revolution Sounds (formally of the Maze) and Rat Cat. Complete with a private, full-sized bar, this huge area can be organised to your liking and is suitable for a range of events including wedding receptions and corporate meetings.
The Castle Rock Team Party is held here every year, and the space is put to good use for Castle Rock’s annual Yard Party.
Sound system
Projector
Free WiFi
Plasma TV
Dining and buffet packages available
',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Sanctuary',
                'location' => 'Sanctuary Rock Bar, Cow Lane, Burnley, UK',
                'postal_town' => 'Burnley',
                'longitude' => '-2.2465192',
                'latitude' => '53.789685',
                'w3w' => 'terms.gallons.straw',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01282459595',
                'contact_email' => 'sanctuaryrockbar@gmail.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/sanctuary.burnley\\"}"',
                'description' => '3 floor multi-genre live music venue, with an incredible, warm & friendly atmosphere like no other.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'The Scene',
                'location' => 'The Scene, Newland, Lincoln, UK',
                'postal_town' => 'Lincoln',
                'longitude' => '-0.5444655',
                'latitude' => '53.2303383',
                'w3w' => 'list.trips.news',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01522569677',
                'contact_email' => 'info@thescenelincoln.com',
                'contact_link' => '"{\\"website\\":\\"https://thescene.club/\\",\\"facebook\\":\\"https://www.facebook.com/TheSceneLincoln\\"}"',
                'description' => 'Lincoln\'s Premier LGBTQ+ Venue 🏳️‍🌈

Check our website for all upcoming events!',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Akedo Bar',
                'location' => 'Akēdo Gaming Bar Lincoln, Corporation Street, Lincoln, UK',
                'postal_town' => 'Lincoln',
                'longitude' => '-0.5404526',
                'latitude' => '53.2304939',
                'w3w' => 'topic.evenly.copy',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01522274200',
                'contact_email' => 'akedoakedo2016@gmail.com',
                'contact_link' => '"{\\"website\\":\\"https://www.akedogamingbar.com/\\",\\"facebook\\":\\"https://www.facebook.com/akedogamingbar\\"}"',
                'description' => 'Akēdo Remastered is coming',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'The Engine Shed',
                'location' => 'The Engine Shed, Lincoln, UK',
                'postal_town' => 'Lincoln',
                'longitude' => '-0.5455222',
                'latitude' => '53.2272875',
                'w3w' => 'fallen.jolly.twin',
                'capacity' => '950',
                'in_house_gear' => '730m Squared Space',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01522837400',
                'contact_email' => 'hire@engineshed.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://engineshed.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/engineshed/\\",\\"instagram\\":\\"https://www.instagram.com/engineshed/\\",\\"twitter\\":\\"https://twitter.com/engineshed\\"}"',
                'description' => 'Leading the way for live music & entertainment in Lincoln......',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'The Six Six Bar',
                'location' => 'The Six Six Bar, East Road, Cambridge, UK',
                'postal_town' => 'Cambridge',
                'longitude' => '0.1311545',
                'latitude' => '52.2025469',
                'w3w' => 'rates.universally.petal',
                'capacity' => '180',
            'in_house_gear' => 'Mackie DL16S (16 channel) digital mixer using Master Fader 5 app as an interface. This is run from an iPad, alternatively touring engineers can bring and use any device that supports WiFi connection and is compatible with either Mackie Master Fader 5 app or Mix Station app, 2x HH HPT-115 PA Speaker, 2x HH HPS-1 15 Sub Woofer, Stage Monitoring: 3x Yamaha DHR12M Active Monitors, Backline: 1x Blackstar ID:100 Guitar Amp (DI compatible), 1x Blackstar S1-413a Guitar Cab, 1x Orange PPC212V Guitar Cab, 4x DI Boxes, 1x Pearl Export Drum Kit (Kick, Snare, 2x Rack Tom, 1x Floor Tom), 4x Cymbal Stands inc Hi Hat stand, 1x Mapex Drum Throne ,Drummers will need to bring ALL breakables. This includes; Cymbals (plus any extra stands you may need), Hi Hat Clutch, Kick Drum Pedal. Microphones: Drum Mics - 1x AKG D112 MkII, 5x Shure e604, Instrument Mics - 2x Sennheiser e609, 2x Shure SM57, Vocal Mics - 1x Shure SM58 Beta, 4x Shure SM58',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'info@thesixsixbars.com',
                'contact_link' => '"{\\"website\\":\\"https://www.thesixsixbars.com/\\",\\"facebook\\":\\"https://www.facebook.com/TheSixSixBar\\",\\"instagram\\":\\"https://www.instagram.com/thesixsixbar/\\"}"',
                'description' => 'Independent Grassroots Music Venue & Rock Bar.

The Home of Rock n Roll for Cambridgeshire.

"The Viper Room of the UK". Thomas Nicholas - American Pie . 2024

The Number 1 supporters of Grassroots Live Music in Cambridgeshire.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'The Portland Arms',
                'location' => 'The Portland Arms, Chesterton Road, Cambridge, UK',
                'postal_town' => 'Cambridge',
                'longitude' => '0.1230356',
                'latitude' => '52.2137173',
                'w3w' => 'habit.sharp.loss',
                'capacity' => '200',
                'in_house_gear' => 'PA, Lighting Rig, Green Room, Online Tickets, Sound Tech',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01223357268',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{}"',
                'description' => 'The official pages for The Portland Arms pub & live music venue in Cambridge.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'The Bullingdon',
                'location' => 'The Bullingdon, Cowley Road, Oxford, UK',
                'postal_town' => 'Oxford',
                'longitude' => '-1.2359377',
                'latitude' => '51.7473899',
                'w3w' => 'once.buzz.healers',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'info@thebullingdon.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://www.thebullingdon.co.uk/index_2022.php\\",\\"facebook\\":\\"https://www.facebook.com/TheBullingdon\\",\\"twitter\\":\\"https://twitter.com/TheBullingdon\\"}"',
                'description' => 'Oxfords leading independent venue
Gigs + Club Nights + Comedy and more
Gig Bookings - info@thebullingdon.co.uk',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Rebellion',
                'location' => 'Rebellion Manchester, Whitworth Street West, Manchester, UK',
                'postal_town' => 'Manchester',
                'longitude' => '2.2504973',
                'latitude' => '53.4742652',
                'w3w' => 'probe.expect.angel',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'BOOKINGS@REBELLION.CLUB',
                'contact_link' => '"{}"',
                'description' => 'The dark side of deansgate',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Grand Central',
                'location' => 'Grand Central Alt Bar & Live Music Venue, 80 Oxford Street, Manchester, UK',
                'postal_town' => 'Manchester',
                'longitude' => '-0.14608',
                'latitude' => '51.51475',
                'w3w' => 'little.tips.final',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'Robin',
                'contact_number' => '01612360890',
                'contact_email' => 'Robin@grandcentralmanchester.com',
                'contact_link' => '"{\\"website\\":\\"https://www.grandcentralmanchester.com/\\",\\"facebook\\":\\"https://www.facebook.com/thegrandcentralmcr/\\",\\"instagram\\":\\"https://www.instagram.com/grandcentralmcr\\",\\"twitter\\":\\"https://twitter.com/grandcentralmcr\\"}"',
                'description' => 'Alternative bar and live music space with weekly live shows and DJs playing the best in alt, rock and metal.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Mama Liz\'s',
                'location' => 'Mama Liz\'s, North Street, Stamford, UK',
                'postal_town' => 'Stamford',
                'longitude' => '-0.4779055',
                'latitude' => '52.6539883',
                'w3w' => 'rising.audit.paper',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01780765888',
                'contact_email' => 'bookings@mamaliz.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://mamaliz.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/profile.php?id=100089377704622\\"}"',
                'description' => 'Now open Wednesday - Sunday, 12 - late.
See www.mamaliz.co.uk for our lunch and dinner menus plus all of our entertainment events.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Trillians',
                'location' => 'Trillians Rock Bar, Princess Square, Newcastle upon Tyne, UK',
                'postal_town' => 'Newcastle',
                'longitude' => '-1.61396',
                'latitude' => '54.97328',
                'w3w' => 'test.swing.could',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '07710095238',
                'contact_email' => 'info@trilliansnewcastle.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://trilliansnewcastle.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/trilliansrockbar\\",\\"instagram\\":\\"https://www.instagram.com/trilliansrocks/\\",\\"twitter\\":\\"https://twitter.com/trilliansrock\\"}"',
                'description' => 'Rock bar',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Railway Tavern',
                'location' => 'Railway Tavern, High Northgate, Darlington, UK',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5521242',
                'latitude' => '54.5320352',
                'w3w' => 'tester.turkey.trace',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'Anki Findlater',
                'contact_number' => '01325464963',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/railwaytavernpub\\"}"',
                'description' => 'Possibly the first \' Railway \' pub in the world which opened in 1827 to serve passengers of the two-year old Stockton & Darlington Railway',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Head Of Steam',
                'location' => 'The Head of Steam Newcastle, Neville Street, Newcastle upon Tyne, UK',
                'postal_town' => 'Newcastle',
                'longitude' => '-1.6155307',
                'latitude' => '54.9695715',
                'w3w' => 'whips.mild.stray',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01912304236',
                'contact_email' => 'newcastle@theheadofsteam.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.theheadofsteam.co.uk/bars/newcastle\\",\\"twitter\\":\\"http://www.twitter.com/HOS_Newcastle\\",\\"instagram\\":\\"https://www.instagram.com/HOS_NEWCASTLE\\"}"',
                'description' => 'Since it’s inception in 1996, The Head of Steam Newcastle has cemented itself as a firm favourite in Newcastle. Situated right across from Newcastle Central Station.
The Head of Steam Newcastle has gained notoriety for hosting the best in up-to-the-minute music. Combining both the venues welcoming atmosphere and warm surroundings with an emphasis on musical brilliance the Head of Steam Newcastle has proved a popular breeding ground for talent.
Offering The Head of Steam’s celebrated selection of exceptional local craft beer and real ale as well as boasting breweries from all around the world, an array of cocktails, spirits and environmentally conscious wine as well as hot drinks.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Penny Gill',
                'location' => 'The Penny Gill, Cheapside, Spennymoor, UK',
                'postal_town' => 'Spennymoor',
                'longitude' => '-1.6004208',
                'latitude' => '54.6999723',
                'w3w' => 'incremet.sleeper.gosh',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01388818849',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/pennygillrockbar/\\"}"',
                'description' => 'Top Rock Bar in Spennymoor, County Durham. Hosting Live Music, Open-Mic, Karaoke and Quiz Nights Eve',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'The Forum Music Studios',
                'location' => 'The Forum Music Studios, Borough Road, Darlington, UK',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5473876',
                'latitude' => '54.5282193',
                'w3w' => 'grow.older.trace',
                'capacity' => '200',
            'in_house_gear' => 'Stage: 12ft x 28ft x 2ft aluminium stage made up of 12 stage blocks with a removable 6ft x 8ft drum riser, Sound: Yamaha M7CL-48 Console (Main), D&b audiotechnik C7 Top x4 D&b audiotechnik C7 Sub x4 D&b audiotechnik D80 Amp x2 28x channels to stage (microphone inputs) 8x aux sends to stage (monitor outputs), Monitors: Mackie SRM 450 active x9, Power: 10x 13 amp at back of stage, 6x 13 amp trailing sockets at front of stage 3 Phase Power Supply 32amp Ceeform Power Supply In Use, AV: CD Player Sanyo Projector (VGA) 110” Screen (4:3) PTZ Optics HD Camera System Apple MacMini, Cinema System: Mackie HR624 Satellite Speakers Mackie SR120 Subwoofer Optoma 720p HD Projector (HDMI) 160” Screen (16:9) Blu-ray Player, Lighting: LightShark LS-1 Console SV PixelBeam 160 x4 SV MH-200 Pro Spot x6 ADJ Hex Wash 7 x2 ADJ Inno ColorBeam 12 x2 ADJ Megabar Pro x2 SV ShowBar TriLED x10 SV LED Flood Panel x6 SV LED Par56 x4 SV LED Par64 x6 SV AF-180 LED Fogger x2 Antari F1 Fazer (Lighting plan available upon request), Microphones: Shure SM58 x12 Shure SM57 x8 Shure PG56 x2 Sennheiser E604 x8 Sennheiser E914 x2 SE SE8 x2 AKG D112 x2 Sennheiser XSW-1 with SKM 825 (Wireless) x4 Sennheiser SK-XSW with ME2 Lavalier Mic x4 Shure PG58 (Wireless) x1 EMO Passive DI x4 BSS Active DI x5, Backline (Available Upon Request): Drum Kit: 5 Piece Pearl Vision 22” Bass Drum, 10” Rack Tom, 12” Rack Tom, “16 Floor Tom, 14” Snare Drum 1x Single Bass Drum Pedal, 1x Hi-Hat Stand, 1x Snare Stand, 2x Boom Cymbal Stand, 1x Straight Cymbal Stand, 1x Drum Throne, Bass Amp: 1x Fender Rumble 100 Combo, Guitar Amp: 1x Marshall Valve State AVT2000 Combo 2x Laney LX65R Combo 2x Crate GT65 Combo, Keyboard: 1x Yamaha P45 Electric Piano, Cabs: 1x Trace Elliot 15” Bass Cab 2x Marshall 4x12” Guitar Cab',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'June/ Kristen',
                'contact_number' => '01325363135',
                'contact_email' => 'info@theforumonline.co.uk',
                'contact_link' => '"{\\"website\\":\\"https:\\\\/\\\\/theforumonline.co.uk\\\\/\\",\\"twitter\\":\\"https:\\\\/\\\\/twitter.com\\\\/TheForum_Music\\",\\"youtube\\":\\"https:\\\\/\\\\/www.youtube.com\\\\/channel\\\\/UCgbACeh4kIJKKAgMEe_gKQQ\\",\\"facebook\\":\\"https:\\\\/\\\\/www.facebook.com\\\\/theforummusicstudios\\\\/\\",\\"instagram\\":\\"https:\\\\/\\\\/www.instagram.com\\\\/theforumdarlington\\\\/\\"}"',
                'description' => 'Darlington\'s Home Of Live Music\' with Cafe/Bar, Performance Hall, Film,Comedy & R\'n\'B Clubs',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-04-05 12:03:05',
                'deleted_at' => NULL,
                'is_verified' => 1,
                'verified_at' => '2025-04-02 22:15:02',
                'preferred_contact' => 'email',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'The Underground',
                'location' => 'The Underground, Duke Street, Bradford, UK',
                'postal_town' => 'Bradford',
                'longitude' => '-1.7542856',
                'latitude' => '53.7959184',
                'w3w' => 'again.less.thank',
                'capacity' => '350',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'Matt',
                'contact_number' => '00000000000',
                'contact_email' => 'matt@theundergroundbradford.com',
                'contact_link' => '"{\\"website\\":\\"https://www.undergroundbradford.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/theundergroundbradford\\",\\"instagram\\":\\"https://www.instagram.com/theundergroundbradford/\\",\\"tiktok\\":\\"https://www.tiktok.com/@theugbradford\\"}"',
                'description' => 'Bradford\'s Grassroots Live Music Venue
Live Music // Drinks // Good Vibes',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Night Train',
                'location' => 'Nightrain, Queensgate, Bradford, UK',
                'postal_town' => 'Bradford',
                'longitude' => '-1.75206',
                'latitude' => '53.79391',
                'w3w' => 'copper.spicy.blend',
                'capacity' => '400',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'Keith Tempest',
                'contact_number' => '01274734239',
                'contact_email' => 'keith.tempest@nightrain.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://nightrain.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/NightrainBradford\\",\\"tiktok\\":\\"https://www.tiktok.com/@nightrainbradford\\",\\"instagram\\":\\"https://www.instagram.com/nightrainbradford/\\",\\"twitter\\":\\"https://www.twitter.com/NightrainVenue\\"}"',
                'description' => 'Keeping Live Music Alive with Grassroots, Tribute and Touring Bands.
🎵 DJ’s at weekends till 3',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => '1in12',
                'location' => '1 In 12 Club, Albion Street, Bradford, UK',
                'postal_town' => 'Bradford',
                'longitude' => '-1.7581442',
                'latitude' => '53.7945342',
                'w3w' => 'tubes.fails.shadow',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'oneintwelve@riseup.net',
                'contact_link' => '"{\\"website\\":\\"https://1in12club.wordpress.com/\\",\\"facebook\\":\\"https://www.facebook.com/1in12/\\"}"',
                'description' => 'The 1 in 12 club since 1981',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'The Gryphon',
                'location' => 'The Gryphon, 41 Colston Street, Bristol, UK',
                'postal_town' => 'Bristol',
                'longitude' => '-2.597745',
                'latitude' => '51.455444',
                'w3w' => 'facing.spices.being',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '07894239567',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/gryphonbristol\\"}"',
                'description' => 'Bristol’s Premier Real Ale & Metal Pub. “BEST PUB IN BRISTOL” Award 2019. 13 Years in the CAMRA GBG',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'The Quakerhouse',
                'location' => 'The Quakerhouse, 2 Mechanics Yard, Darlington, DL3 7QF, England',
                'postal_town' => 'Darlington',
                'longitude' => '-1.556147813797',
                'latitude' => '54.524459838867',
                'w3w' => 'outer.desk.visa',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01325245052',
                'contact_email' => 'info@quakerhouse.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://quakerhouse.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/TheQuakerhouse\\",\\"instagram\\":\\"https://www.instagram.com/thequakerhouse/\\"}"',
                'description' => 'The Quakerhouse opened as a Licensed Bar in October 1998 having undergone major alterations from the old Quaker Coffee House. The building was originally 3 cottages built in the late 1700’s when the yard was active with tradesmen such as coopers and blacksmiths.

Mechanics Yard as it is known now used to be known as Betty Hobson’s yard, indeed it is thought that Betty still haunts the yard. Whether there is any connection between this and our resident ghost, Ethel, we can’t be sure but there are plenty of stories going around, so draw your own conclusions.',
                'packages' => NULL,
                'additional_info' => 'Free function room hire',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Voodoo Cafe',
                'location' => '84 Skinnergate, Darlington, DL3 7LX, United Kingdom',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5575066',
                'latitude' => '54.5240892',
                'w3w' => 'tests.labels.wires',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01325467555',
                'contact_email' => 'voodoocafebookings@yahoo.com',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/voodoocafedarlington/\\",\\"instagram\\":\\"https://www.instagram.com/voodoocafebar/\\"}"',
                'description' => 'Award winning Mexican S/American themed restaurant, Cafe/Bar, Amazing cocktails and a huge selection of imported beers. Salsa, Tango, Live Music venue. ',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Vesuvio',
                'location' => 'Vesuvio, 3A Houndgate, Darlington, DL1 5RL, United Kingdom',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5564156',
                'latitude' => '54.5235617',
                'w3w' => 'expert.moves.orbit',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '07599461588',
                'contact_email' => 'info@vesuviowines.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/VesuvioWineBar\\",\\"instagram\\":\\"https://www.instagram.com/vesuviowines/\\"}"',
                'description' => 'VESUVIO - “The Tavern in the Town”
• Fine Wines, Craft & Real Ales, Premium Spirits
• Bespoke Cocktails prepared by acclaimed cocktail master @Les Fry
• New restaurant plans coming!
• Wine & Bottle Sales',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Darlington Hippodrome',
                'location' => 'Darlington Hippodrome, Parkgate, Darlington, DL1 1RR, United Kingdom',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5485127',
                'latitude' => '54.5246283',
                'w3w' => 'healthier.begun.chief',
                'capacity' => '1000',
                'in_house_gear' => 'Darlington Hippodrome can accommodate a range of different meetings and events, from a boardroom style meeting for 10 people to large conference for 1000 people.
For meetings & smaller events, we can offer the following items on request, all included in the room hire price:
• Laptop
• Projector
• Screen
• Flipcharts, paper and pens
For larger auditorium hires, our technical team can accommodate a wide range of technical set-ups for bespoke events.
',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01325405405',
                'contact_email' => 'hires.hippodrome@darlington.gov.uk',
                'contact_link' => '"{\\"website\\":\\"https://www.darlingtonhippodrome.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/darlingtonhippodrome\\",\\"twitter\\":\\"https://x.com/DarlingtonHipp\\",\\"instagram\\":\\"https://www.instagram.com/darlingtonhippodrome/\\",\\"tiktok\\":\\"https://www.tiktok.com/@darlingtonhippodrome\\"}"',
                'description' => 'Darlington Hippodrome is a 1000-seat Edwardian era theatre.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'The Old English Gentleman',
                'location' => 'Old English Gentleman, 99 Bondgate, Darlington, DL3 7JY, England',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5566132068634',
                'latitude' => '54.526550292969',
                'w3w' => 'stay.dates.diary',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/TheNewOldEnglishGentleman\\",\\"instagram\\":\\"https://www.instagram.com/theoldenglishgentleman/\\"}"',
                'description' => 'Welcome to The Old English Gentleman, Traditional Pub With Values..👌
Our Customers Make Their Pub Amazing!! 😄
SUPPORTING Our Local Community!!!
#loveourregulars ❤️',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'The Turks Head',
                'location' => 'The Turks Head, 21-22 Bondgate, Darlington, DL3 7JG, United Kingdom',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5575143',
                'latitude' => '54.5263013',
                'w3w' => 'robots.picked.decks',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["original-bands", "cover-bands"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01325463191',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/turkshead.darlington.35/\\",\\"instagram\\":\\"https://www.instagram.com/turksheaddarlington/\\"}"',
                'description' => 'Hours may vary
Children welcome till 5pm
DOGs ALLOWED till 6pm in beer garden only must be kept on leash and mess put in appropriate bin
HEAVY ROCK BAR',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'The Pennyweight',
                'location' => 'The Pennyweight, 8 Bakehouse Hill, Darlington, DL1 5QA, United Kingdom',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5539083',
                'latitude' => '54.5245894',
                'w3w' => 'play.librarian.arch',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '01325468411',
                'contact_email' => 'enquiries@thepennyweight.co.uk',
                'contact_link' => '"{\\"website\\":\\"https://www.thepennyweight.co.uk/\\",\\"facebook\\":\\"https://www.facebook.com/ThePennyweight\\",\\"instagram\\":\\"https://www.instagram.com/thepennyweight/\\"}"',
                'description' => 'A iconic british pub, serving the most hearty food choice around! Alongside our fantastic real ale selection & of course a huge drinks selection!',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'The Quays',
                'location' => 'The Quays, Tubwell Row, Darlington, DL1 5PZ, United Kingdom',
                'postal_town' => 'Darlington',
                'longitude' => '-1.554666',
                'latitude' => '54.5250712',
                'w3w' => 'laser.curvy.advice',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '0000000000',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/profile.php?id=100089886230487\\"}"',
                'description' => 'Monday-Thursday 9-2.30am Friday-Sunday 7-2.30am LIVE DJS EVERY NIGHT',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Hole in the Wall',
                'location' => 'Hole In The Wall, 15 Horsemarket, Darlington, DL1 5PT, United Kingdom',
                'postal_town' => 'Darlington',
                'longitude' => '-1.5545874',
                'latitude' => '54.5240238',
                'w3w' => 'honey.bunch.lease',
                'capacity' => '0',
                'in_house_gear' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'deposit_required' => NULL,
                'deposit_amount' => NULL,
                'band_type' => '["all"]',
                'genre' => '{}',
                'contact_name' => 'General',
                'contact_number' => '00000000000',
                'contact_email' => 'blank@yournextshow.co.uk',
                'contact_link' => '"{\\"facebook\\":\\"https://www.facebook.com/profile.php?id=61568574835726\\",\\"instagram\\":\\"https://www.instagram.com/hitwdarlington/\\"}"',
                'description' => 'Traditional town centre pub with a great selection of real ale, craft beer, wine and spirits - not to mention our fantastic food menus.',
                'packages' => NULL,
                'additional_info' => 'This is a placeholder section. We don’t have anything here right now but bare with us, we’re working on it!',
                'logo_url' => 'https://linktothelogo.com/logo.png',
                'created_at' => '2025-03-31 20:37:53',
                'updated_at' => '2025-03-31 20:37:53',
                'deleted_at' => NULL,
                'is_verified' => 0,
                'verified_at' => NULL,
                'preferred_contact' => NULL,
            ),
        ));
        
        
    }
}