<?php

return [
    'styles' => [
        'Large Format',
        'Commercial',
        'Conceptual',
        'Fine Art',
        'Street',
        'Aesthetic',
        'Landscape',
        'Editorial',
        'Contract',
        'Sepia Tone',
        'Sports',
        'Natural Light',
        'Black and White',
        'Glamour',
        'Wedding',
        'Portrait',
        'Film',
        'Event',
        'Fashion',
        'Nature',
    ],
    'conditions' => [
        'Dark Environments',
        'Light Environments',
        'Mixed Lighting',
        'Backlit Scenes',
    ],
    'locations' => [
        'Outside (Day)',
        'Outside (Night)',
        'Inside',
        'Studio',
    ],
    'settings' => [
        'Forests',
        'Beaches',
        'Mountains',
        'Urban Nature (Parks, Gardens)',
    ],
    'times' => [
        'Golden Hour',
        'Blue Hour',
        'Midday',
        'Twilight',
    ],
    'contexts' => [
        'Fashion and Modeling',
        'Family Portraits',
        'Couple Portraits',
        'Children’s Photography',
        'Corporate Headshots',
        'Actors/Models Headshots',
    ],
];